//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common_ActivityLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_ActivityLogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common_ActivityLogs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Details.
        /// </summary>
        internal static string Grid_Link_Title_Details {
            get {
                return ResourceManager.GetString("Grid_Link_Title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Action.
        /// </summary>
        internal static string Grid_Title_ActivityAction {
            get {
                return ResourceManager.GetString("Grid_Title_ActivityAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string Grid_Title_Changes {
            get {
                return ResourceManager.GetString("Grid_Title_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Date.
        /// </summary>
        internal static string Grid_Title_Date {
            get {
                return ResourceManager.GetString("Grid_Title_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performed By.
        /// </summary>
        internal static string Grid_Title_PerformedBy {
            get {
                return ResourceManager.GetString("Grid_Title_PerformedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Grid_Title_Section {
            get {
                return ResourceManager.GetString("Grid_Title_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Time.
        /// </summary>
        internal static string Grid_Title_Time {
            get {
                return ResourceManager.GetString("Grid_Title_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Log Changes.
        /// </summary>
        internal static string Popup_Title_Details {
            get {
                return ResourceManager.GetString("Popup_Title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Log.
        /// </summary>
        internal static string Section_Title {
            get {
                return ResourceManager.GetString("Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Text_Value {
            get {
                return ResourceManager.GetString("Text_Value", resourceCulture);
            }
        }
    }
}
