//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common_ApplicationStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_ApplicationStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common_ApplicationStatus", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        internal static string Grid_Title_ApprovedDate {
            get {
                return ResourceManager.GetString("Grid_Title_ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Date.
        /// </summary>
        internal static string Grid_Title_AssignedDate {
            get {
                return ResourceManager.GetString("Grid_Title_AssignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Name.
        /// </summary>
        internal static string Grid_Title_AuthorizedName {
            get {
                return ResourceManager.GetString("Grid_Title_AuthorizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Person.
        /// </summary>
        internal static string Grid_Title_AuthorizedPerson {
            get {
                return ResourceManager.GetString("Grid_Title_AuthorizedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Grid_Title_Comments {
            get {
                return ResourceManager.GetString("Grid_Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Grid_Title_Departments {
            get {
                return ResourceManager.GetString("Grid_Title_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string Grid_Title_DueDate {
            get {
                return ResourceManager.GetString("Grid_Title_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string Grid_Title_Levels {
            get {
                return ResourceManager.GetString("Grid_Title_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Grid_Title_Person {
            get {
                return ResourceManager.GetString("Grid_Title_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Person.
        /// </summary>
        internal static string Grid_Title_ResponsiblePerson {
            get {
                return ResourceManager.GetString("Grid_Title_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Grid_Title_Role {
            get {
                return ResourceManager.GetString("Grid_Title_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Title_Status {
            get {
                return ResourceManager.GetString("Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Days.
        /// </summary>
        internal static string Grid_Title_TotalDays {
            get {
                return ResourceManager.GetString("Grid_Title_TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Department.
        /// </summary>
        internal static string Section_ResponsibleDepartment {
            get {
                return ResourceManager.GetString("Section_ResponsibleDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Status.
        /// </summary>
        internal static string Section_Title {
            get {
                return ResourceManager.GetString("Section_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver Matrix.
        /// </summary>
        internal static string Section_Title_ApproverMatrix {
            get {
                return ResourceManager.GetString("Section_Title_ApproverMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Assigned.
        /// </summary>
        internal static string Text_NotAssigned {
            get {
                return ResourceManager.GetString("Text_NotAssigned", resourceCulture);
            }
        }
    }
}
