//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Task.
        /// </summary>
        internal static string Button_CopyTask {
            get {
                return ResourceManager.GetString("Button_CopyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string Button_Text_AddTask {
            get {
                return ResourceManager.GetString("Button_Text_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected Cache Object.
        /// </summary>
        internal static string Button_Text_ClearCache {
            get {
                return ResourceManager.GetString("Button_Text_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Text_Close {
            get {
                return ResourceManager.GetString("Button_Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button_Text_Confirm {
            get {
                return ResourceManager.GetString("Button_Text_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Button_Text_Exit {
            get {
                return ResourceManager.GetString("Button_Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Button_Text_Print {
            get {
                return ResourceManager.GetString("Button_Text_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Text_Save {
            get {
                return ResourceManager.GetString("Button_Text_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Button_Text_Search {
            get {
                return ResourceManager.GetString("Button_Text_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate LSMW.
        /// </summary>
        internal static string Button_Title_GenerateLSMW {
            get {
                return ResourceManager.GetString("Button_Title_GenerateLSMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Button_Title_Select {
            get {
                return ResourceManager.GetString("Button_Title_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Start Date is required..
        /// </summary>
        internal static string Error_ActualStartDate {
            get {
                return ResourceManager.GetString("Error_ActualStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required (Minimum Length should be 15, maximum should not greater than 1000.).
        /// </summary>
        internal static string Error_Comment {
            get {
                return ResourceManager.GetString("Error_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found..
        /// </summary>
        internal static string Grid_Text_NoData {
            get {
                return ResourceManager.GetString("Grid_Text_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Grid_Title_Action {
            get {
                return ResourceManager.GetString("Grid_Title_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Grid_Title_CacheKey {
            get {
                return ResourceManager.GetString("Grid_Title_CacheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string Grid_Title_RequestDate {
            get {
                return ResourceManager.GetString("Grid_Title_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. No..
        /// </summary>
        internal static string Grid_Title_SrNo {
            get {
                return ResourceManager.GetString("Grid_Title_SrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Title_Status {
            get {
                return ResourceManager.GetString("Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Label_ApprovalDate {
            get {
                return ResourceManager.GetString("Label_ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment:.
        /// </summary>
        internal static string Label_Attachment {
            get {
                return ResourceManager.GetString("Label_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string Label_EmailAddress {
            get {
                return ResourceManager.GetString("Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword:.
        /// </summary>
        internal static string Label_Keyword {
            get {
                return ResourceManager.GetString("Label_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark CC:.
        /// </summary>
        internal static string Label_MarkCC {
            get {
                return ResourceManager.GetString("Label_MarkCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No:.
        /// </summary>
        internal static string Label_MobileNo {
            get {
                return ResourceManager.GetString("Label_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        internal static string Label_Month {
            get {
                return ResourceManager.GetString("Label_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code:.
        /// </summary>
        internal static string Label_PostalCode {
            get {
                return ResourceManager.GetString("Label_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status:.
        /// </summary>
        internal static string Label_TaskStatus {
            get {
                return ResourceManager.GetString("Label_TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone No:.
        /// </summary>
        internal static string Label_Telephone {
            get {
                return ResourceManager.GetString("Label_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string Label_Year {
            get {
                return ResourceManager.GetString("Label_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        internal static string Page_CacheTitle {
            get {
                return ResourceManager.GetString("Page_CacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Section_Title_ResponsibleDepartment {
            get {
                return ResourceManager.GetString("Section_Title_ResponsibleDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Text_Company {
            get {
                return ResourceManager.GetString("Text_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Text_Draft {
            get {
                return ResourceManager.GetString("Text_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Text_Field {
            get {
                return ResourceManager.GetString("Text_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Scheduled in TMS.
        /// </summary>
        internal static string Text_FromTMS {
            get {
                return ResourceManager.GetString("Text_FromTMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field marked with &apos;*&apos; are mandatory.
        /// </summary>
        internal static string Text_Mandatory {
            get {
                return ResourceManager.GetString("Text_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string Text_Mr {
            get {
                return ResourceManager.GetString("Text_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. and Mrs..
        /// </summary>
        internal static string Text_Mrs {
            get {
                return ResourceManager.GetString("Text_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        internal static string Text_Ms {
            get {
                return ResourceManager.GetString("Text_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string Text_NA {
            get {
                return ResourceManager.GetString("Text_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Non Scheduled.
        /// </summary>
        internal static string Text_NonSchedule {
            get {
                return ResourceManager.GetString("Text_NonSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Note: Please print document with A4 size for better result..
        /// </summary>
        internal static string Text_Print {
            get {
                return ResourceManager.GetString("Text_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        internal static string Text_Requester {
            get {
                return ResourceManager.GetString("Text_Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is Required..
        /// </summary>
        internal static string Text_SendBackCommentRequired {
            get {
                return ResourceManager.GetString("Text_SendBackCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Text_Value {
            get {
                return ResourceManager.GetString("Text_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
    }
}
