//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DCN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DCN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DCN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string Button_Text_Add {
            get {
                return ResourceManager.GetString("Button_Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document.
        /// </summary>
        internal static string Button_Text_AddSpecification {
            get {
                return ResourceManager.GetString("Button_Text_AddSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DCR.
        /// </summary>
        internal static string Button_Title_SelectDCR {
            get {
                return ResourceManager.GetString("Button_Title_SelectDCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Approve/Rework.
        /// </summary>
        internal static string Error_ApproveRework {
            get {
                return ResourceManager.GetString("Error_ApproveRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component is required.
        /// </summary>
        internal static string Error_Component {
            get {
                return ResourceManager.GetString("Error_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component/Raw Material is required (Max 255 characters)..
        /// </summary>
        internal static string Error_ComponentRawMaterial {
            get {
                return ResourceManager.GetString("Error_ComponentRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Date is required.
        /// </summary>
        internal static string Error_Dateofimplementation {
            get {
                return ResourceManager.GetString("Error_Dateofimplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR No is required.
        /// </summary>
        internal static string Error_DCRNo {
            get {
                return ResourceManager.GetString("Error_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Approve/Rework..
        /// </summary>
        internal static string Error_DCRProcessICApproveRework {
            get {
                return ResourceManager.GetString("Error_DCRProcessICApproveRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DCRProcessIComment {
            get {
                return ResourceManager.GetString("Error_DCRProcessIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DCRProcessInchargeComment {
            get {
                return ResourceManager.GetString("Error_DCRProcessInchargeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Change date is required.
        /// </summary>
        internal static string Error_DesignchangerequiredbyDate {
            get {
                return ResourceManager.GetString("Error_DesignchangerequiredbyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DesignEngComment {
            get {
                return ResourceManager.GetString("Error_DesignEngComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No is required.
        /// </summary>
        internal static string Error_DocumentNo {
            get {
                return ResourceManager.GetString("Error_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Title is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DocumentTitle {
            get {
                return ResourceManager.GetString("Error_DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No. is required.
        /// </summary>
        internal static string Error_FileNameList {
            get {
                return ResourceManager.GetString("Error_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Specification Attachment is required..
        /// </summary>
        internal static string Error_FNLPresentSpecification1 {
            get {
                return ResourceManager.GetString("Error_FNLPresentSpecification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Specification Attachment is required..
        /// </summary>
        internal static string Error_FNLRevisedSpecification1 {
            get {
                return ResourceManager.GetString("Error_FNLRevisedSpecification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date is required.
        /// </summary>
        internal static string Error_Issuedate {
            get {
                return ResourceManager.GetString("Error_Issuedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Specifications is required (Max 255 characters)..
        /// </summary>
        internal static string Error_PresentSpecification {
            get {
                return ResourceManager.GetString("Error_PresentSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date is requred.
        /// </summary>
        internal static string Error_RequestDate {
            get {
                return ResourceManager.GetString("Error_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Specifications is required (Max 255 characters)..
        /// </summary>
        internal static string Error_RevisedSpecification {
            get {
                return ResourceManager.GetString("Error_RevisedSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision No is required (Max 255 characters)..
        /// </summary>
        internal static string Error_RevisionNo {
            get {
                return ResourceManager.GetString("Error_RevisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Product Sr. No. is required (Max length 255 Char.).
        /// </summary>
        internal static string Error_StartProductSrNo {
            get {
                return ResourceManager.GetString("Error_StartProductSrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component/Raw Material.
        /// </summary>
        internal static string Grid_Title_Componentrawmaterial {
            get {
                return ResourceManager.GetString("Grid_Title_Componentrawmaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Date.
        /// </summary>
        internal static string Grid_Title_DateofImplementation {
            get {
                return ResourceManager.GetString("Grid_Title_DateofImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR No.
        /// </summary>
        internal static string Grid_Title_DCRNo {
            get {
                return ResourceManager.GetString("Grid_Title_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string Grid_Title_DocumentNo {
            get {
                return ResourceManager.GetString("Grid_Title_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Title.
        /// </summary>
        internal static string Grid_Title_DocumentTitle {
            get {
                return ResourceManager.GetString("Grid_Title_DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string Grid_Title_Issuedate {
            get {
                return ResourceManager.GetString("Grid_Title_Issuedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Specifications.
        /// </summary>
        internal static string Grid_Title_PresentSpecifications {
            get {
                return ResourceManager.GetString("Grid_Title_PresentSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By.
        /// </summary>
        internal static string Grid_Title_ProposedBy {
            get {
                return ResourceManager.GetString("Grid_Title_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        internal static string Grid_Title_RequestedDate {
            get {
                return ResourceManager.GetString("Grid_Title_RequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Specifications.
        /// </summary>
        internal static string Grid_Title_RevisedSpecifications {
            get {
                return ResourceManager.GetString("Grid_Title_RevisedSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision No..
        /// </summary>
        internal static string Grid_Title_RevisionNo {
            get {
                return ResourceManager.GetString("Grid_Title_RevisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr No.
        /// </summary>
        internal static string Grid_Title_SrNo {
            get {
                return ResourceManager.GetString("Grid_Title_SrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Product Sr. No..
        /// </summary>
        internal static string Grid_Title_StartProductsrno {
            get {
                return ResourceManager.GetString("Grid_Title_StartProductsrno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Grid_Title_Supplier {
            get {
                return ResourceManager.GetString("Grid_Title_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve/Rework:.
        /// </summary>
        internal static string Label_ApproveRework {
            get {
                return ResourceManager.GetString("Label_ApproveRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Incharge:.
        /// </summary>
        internal static string Label_CCIncharge {
            get {
                return ResourceManager.GetString("Label_CCIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Comments:.
        /// </summary>
        internal static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component:.
        /// </summary>
        internal static string Label_Component {
            get {
                return ResourceManager.GetString("Label_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component/Raw Material.
        /// </summary>
        internal static string Label_ComponentRawMaterial {
            get {
                return ResourceManager.GetString("Label_ComponentRawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP Marketing Incharge.
        /// </summary>
        internal static string Label_DAPMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_DAPMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Date:.
        /// </summary>
        internal static string Label_Dateofimplementation {
            get {
                return ResourceManager.GetString("Label_Dateofimplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN No:.
        /// </summary>
        internal static string Label_DCNNo {
            get {
                return ResourceManager.GetString("Label_DCNNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Creator:.
        /// </summary>
        internal static string Label_DCRCreator {
            get {
                return ResourceManager.GetString("Label_DCRCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment :.
        /// </summary>
        internal static string Label_DCRDCNAttachment {
            get {
                return ResourceManager.GetString("Label_DCRDCNAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR No:.
        /// </summary>
        internal static string Label_DCRNo {
            get {
                return ResourceManager.GetString("Label_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve / Rework:.
        /// </summary>
        internal static string Label_DCRProcessICApproveRework {
            get {
                return ResourceManager.GetString("Label_DCRProcessICApproveRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Process Incharge:.
        /// </summary>
        internal static string Label_DCRProcessIncharge {
            get {
                return ResourceManager.GetString("Label_DCRProcessIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Process Incharge Comments:.
        /// </summary>
        internal static string Label_DCRProcessInchargeComment {
            get {
                return ResourceManager.GetString("Label_DCRProcessInchargeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Change note issued on:.
        /// </summary>
        internal static string Label_DesignChangeNoteIssuedOn {
            get {
                return ResourceManager.GetString("Label_DesignChangeNoteIssuedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer.
        /// </summary>
        internal static string Label_DesignEngineer {
            get {
                return ResourceManager.GetString("Label_DesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve/Rework.
        /// </summary>
        internal static string Label_DesignEngineerApproveRework {
            get {
                return ResourceManager.GetString("Label_DesignEngineerApproveRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Incharge : .
        /// </summary>
        internal static string Label_DesignEngineerIncharge {
            get {
                return ResourceManager.GetString("Label_DesignEngineerIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No.:.
        /// </summary>
        internal static string Label_DocumentNo {
            get {
                return ResourceManager.GetString("Label_DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Title:.
        /// </summary>
        internal static string Label_DocumentTitle {
            get {
                return ResourceManager.GetString("Label_DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS Marketing Incharge.
        /// </summary>
        internal static string Label_FANSMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_FANSMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No..
        /// </summary>
        internal static string Label_FileNameList {
            get {
                return ResourceManager.GetString("Label_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Specification File.
        /// </summary>
        internal static string Label_FNLPresentSpecification {
            get {
                return ResourceManager.GetString("Label_FNLPresentSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Specification File.
        /// </summary>
        internal static string Label_FNLRevisedSpecification {
            get {
                return ResourceManager.GetString("Label_FNLRevisedSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Provided By QA:.
        /// </summary>
        internal static string Label_InformationProvidedByQA {
            get {
                return ResourceManager.GetString("Label_InformationProvidedByQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date:.
        /// </summary>
        internal static string Label_Issuedate {
            get {
                return ResourceManager.GetString("Label_Issuedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP Marketing Incharge.
        /// </summary>
        internal static string Label_KAPMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_KAPMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Marketing Incharge.
        /// </summary>
        internal static string Label_LightingMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_LightingMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Marketing Incharge.
        /// </summary>
        internal static string Label_LUMMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_LUMMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Rechard Marketing Incharge.
        /// </summary>
        internal static string Label_MRMarketingIncharge {
            get {
                return ResourceManager.GetString("Label_MRMarketingIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Specifications:.
        /// </summary>
        internal static string Label_PresentSpecification {
            get {
                return ResourceManager.GetString("Label_PresentSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN Issued by:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Date of Approval.
        /// </summary>
        internal static string Label_QADateofApproval {
            get {
                return ResourceManager.GetString("Label_QADateofApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Incharge:.
        /// </summary>
        internal static string Label_QAIncharge {
            get {
                return ResourceManager.GetString("Label_QAIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Department:.
        /// </summary>
        internal static string Label_RequestDepartment {
            get {
                return ResourceManager.GetString("Label_RequestDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Specifications:.
        /// </summary>
        internal static string Label_RevisedSpecification {
            get {
                return ResourceManager.GetString("Label_RevisedSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision No..
        /// </summary>
        internal static string Label_RevisionNo {
            get {
                return ResourceManager.GetString("Label_RevisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM:.
        /// </summary>
        internal static string Label_SCMIncharge {
            get {
                return ResourceManager.GetString("Label_SCMIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Product Sr No.
        /// </summary>
        internal static string Label_StartProductSrNo {
            get {
                return ResourceManager.GetString("Label_StartProductSrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Change Note.
        /// </summary>
        internal static string Label_TitleValue {
            get {
                return ResourceManager.GetString("Label_TitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name:.
        /// </summary>
        internal static string Label_VendorName {
            get {
                return ResourceManager.GetString("Label_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string Label_WorkflowStatus {
            get {
                return ResourceManager.GetString("Label_WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DCR No.
        /// </summary>
        internal static string Popup_Select_DCRNo {
            get {
                return ResourceManager.GetString("Popup_Select_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document.
        /// </summary>
        internal static string Popup_Title_AddRevisedAppDoc {
            get {
                return ResourceManager.GetString("Popup_Title_AddRevisedAppDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Specification.
        /// </summary>
        internal static string Popup_Title_AddSpecification {
            get {
                return ResourceManager.GetString("Popup_Title_AddSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Document.
        /// </summary>
        internal static string Popup_Title_EditRevisedAppDoc {
            get {
                return ResourceManager.GetString("Popup_Title_EditRevisedAppDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Specification.
        /// </summary>
        internal static string Popup_Title_EditSpecification {
            get {
                return ResourceManager.GetString("Popup_Title_EditSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Document Engineer Section.
        /// </summary>
        internal static string Section_Title_DesignDocumentEngineer {
            get {
                return ResourceManager.GetString("Section_Title_DesignDocumentEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Section.
        /// </summary>
        internal static string Section_Title_DesignEngineer {
            get {
                return ResourceManager.GetString("Section_Title_DesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Incharge Section.
        /// </summary>
        internal static string Section_Title_DesignEngineerIncharge {
            get {
                return ResourceManager.GetString("Section_Title_DesignEngineerIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Process Incharge Section.
        /// </summary>
        internal static string Section_Title_ProcessIncharge {
            get {
                return ResourceManager.GetString("Section_Title_ProcessIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Incharge Section.
        /// </summary>
        internal static string Section_Title_QAIncharge {
            get {
                return ResourceManager.GetString("Section_Title_QAIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised Applicable Documents.
        /// </summary>
        internal static string Section_Title_RevisedapplicabledocumentsGrid {
            get {
                return ResourceManager.GetString("Section_Title_RevisedapplicabledocumentsGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM Section.
        /// </summary>
        internal static string Section_Title_SCMSection {
            get {
                return ResourceManager.GetString("Section_Title_SCMSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string Section_Title_SpecificationGrid {
            get {
                return ResourceManager.GetString("Section_Title_SpecificationGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details.
        /// </summary>
        internal static string Section_Title_VendorGrid {
            get {
                return ResourceManager.GetString("Section_Title_VendorGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN Completed successfully.
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DCR No is already in used, Kindly Select another DCR No..
        /// </summary>
        internal static string Text_IsDCNGenerated {
            get {
                return ResourceManager.GetString("Text_IsDCNGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Detail is deleted.
        /// </summary>
        internal static string Text_RevisedAppDocDeleted {
            get {
                return ResourceManager.GetString("Text_RevisedAppDocDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Detail is saved.
        /// </summary>
        internal static string Text_RevisedAppDocSave {
            get {
                return ResourceManager.GetString("Text_RevisedAppDocSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Revised Applicable document is required.
        /// </summary>
        internal static string Text_RevisedApplicableValidation {
            get {
                return ResourceManager.GetString("Text_RevisedApplicableValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN saved successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select DCR No.
        /// </summary>
        internal static string Text_SelectDCRNO {
            get {
                return ResourceManager.GetString("Text_SelectDCRNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN Send Back to Design document engineer for rework..
        /// </summary>
        internal static string Text_SendBackSuccess {
            get {
                return ResourceManager.GetString("Text_SendBackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Detail is deleted.
        /// </summary>
        internal static string Text_SpecificationDeleted {
            get {
                return ResourceManager.GetString("Text_SpecificationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Detail is saved.
        /// </summary>
        internal static string Text_SpecificationSave {
            get {
                return ResourceManager.GetString("Text_SpecificationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one specification/Revised Applicable document is required.
        /// </summary>
        internal static string Text_SpecificationValidation {
            get {
                return ResourceManager.GetString("Text_SpecificationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCN submitted Successfully.
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Detail is deleted.
        /// </summary>
        internal static string Text_VendorDCNDeleted {
            get {
                return ResourceManager.GetString("Text_VendorDCNDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Detail is saved.
        /// </summary>
        internal static string Text_VendorDCNSave {
            get {
                return ResourceManager.GetString("Text_VendorDCNSave", resourceCulture);
            }
        }
    }
}
