//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DCR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DCR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DCR", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor Details.
        /// </summary>
        internal static string Button_Text_AddVendor {
            get {
                return ResourceManager.GetString("Button_Text_AddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit is required..
        /// </summary>
        internal static string Error_BusinessUnit {
            get {
                return ResourceManager.GetString("Error_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required (Max 255 characters)..
        /// </summary>
        internal static string Error_CCIfNotFeasibleGiveReason {
            get {
                return ResourceManager.GetString("Error_CCIfNotFeasibleGiveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_Comment {
            get {
                return ResourceManager.GetString("Error_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments After Proto Testing field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_CommentsAfterProtoTesting {
            get {
                return ResourceManager.GetString("Error_CommentsAfterProtoTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Consider or Rework.
        /// </summary>
        internal static string Error_ConsiderRework {
            get {
                return ResourceManager.GetString("Error_ConsiderRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Increase/Decrease is required (Max length 15 Digit.).
        /// </summary>
        internal static string Error_CostIncreaseDecrease {
            get {
                return ResourceManager.GetString("Error_CostIncreaseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost reduced / Increased by Rs is required.
        /// </summary>
        internal static string Error_CostReducedIncreasedByRs {
            get {
                return ResourceManager.GetString("Error_CostReducedIncreasedByRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Value is required (Max length 15 digit.).
        /// </summary>
        internal static string Error_CostValue {
            get {
                return ResourceManager.GetString("Error_CostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DAPExpectedChange {
            get {
                return ResourceManager.GetString("Error_DAPExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DAPIComment {
            get {
                return ResourceManager.GetString("Error_DAPIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select DAP Marketing User.
        /// </summary>
        internal static string Error_DAPMarketingUser {
            get {
                return ResourceManager.GetString("Error_DAPMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP TO BE CONSIDERED is Required..
        /// </summary>
        internal static string Error_DAPTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_DAPTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Completion of Testing is required.
        /// </summary>
        internal static string Error_DateForCompletionOfTesting {
            get {
                return ResourceManager.GetString("Error_DateForCompletionOfTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Receipt of Samples is required.
        /// </summary>
        internal static string Error_DateForReceiptOfSamples {
            get {
                return ResourceManager.GetString("Error_DateForReceiptOfSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation date is required.
        /// </summary>
        internal static string Error_DateOfImplementation {
            get {
                return ResourceManager.GetString("Error_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer is required.
        /// </summary>
        internal static string Error_DCRDESIGNENGINEERUser {
            get {
                return ResourceManager.GetString("Error_DCRDESIGNENGINEERUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select DCR Incharge.
        /// </summary>
        internal static string Error_DCRIncharge {
            get {
                return ResourceManager.GetString("Error_DCRIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DCRInchargeNavigatorComment {
            get {
                return ResourceManager.GetString("Error_DCRInchargeNavigatorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DCRProcessIComment {
            get {
                return ResourceManager.GetString("Error_DCRProcessIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR to be considered is required.
        /// </summary>
        internal static string Error_DCRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_DCRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for rework is required(Max 255 characters).
        /// </summary>
        internal static string Error_DEIReworkComments {
            get {
                return ResourceManager.GetString("Error_DEIReworkComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Department.
        /// </summary>
        internal static string Error_Department {
            get {
                return ResourceManager.GetString("Error_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of design change proposed field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_DescriptionOfDesignChangePropose {
            get {
                return ResourceManager.GetString("Error_DescriptionOfDesignChangePropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Design change proposed due to.
        /// </summary>
        internal static string Error_Designchangeproposeddueto {
            get {
                return ResourceManager.GetString("Error_Designchangeproposeddueto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reason is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DesignChangeProposedOther {
            get {
                return ResourceManager.GetString("Error_DesignChangeProposedOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design change required by (Date) is required.
        /// </summary>
        internal static string Error_DesignChangeRequiredByDate {
            get {
                return ResourceManager.GetString("Error_DesignChangeRequiredByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Document Engineer is Required..
        /// </summary>
        internal static string Error_DesignDocumentEngineer {
            get {
                return ResourceManager.GetString("Error_DesignDocumentEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer is required..
        /// </summary>
        internal static string Error_DesignEngineer {
            get {
                return ResourceManager.GetString("Error_DesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_DesignEngineerComment {
            get {
                return ResourceManager.GetString("Error_DesignEngineerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Incharge is required.
        /// </summary>
        internal static string Error_DesignEngineerIncharge {
            get {
                return ResourceManager.GetString("Error_DesignEngineerIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in components and assembly field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_Detailsofchangesincomponents {
            get {
                return ResourceManager.GetString("Error_Detailsofchangesincomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in tools, jigs and fixtures field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_Detailsofchangesintoolsjigs {
            get {
                return ResourceManager.GetString("Error_Detailsofchangesintoolsjigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division is required..
        /// </summary>
        internal static string Error_Division {
            get {
                return ResourceManager.GetString("Error_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect on cost of part and product is required.
        /// </summary>
        internal static string Error_EffectOnCostOfPartAndProduct {
            get {
                return ResourceManager.GetString("Error_EffectOnCostOfPartAndProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect on performance field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_Effectonperformance {
            get {
                return ResourceManager.GetString("Error_Effectonperformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Component Stock is required..
        /// </summary>
        internal static string Error_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Error_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected effect of change on sales field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_Expectedeffectofchangeonsales {
            get {
                return ResourceManager.GetString("Error_Expectedeffectofchangeonsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected results if design change is carried out field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_Expectedresultsifdesignchangeisc {
            get {
                return ResourceManager.GetString("Error_Expectedresultsifdesignchangeisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_FANIComment {
            get {
                return ResourceManager.GetString("Error_FANIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_FANSExpectedChange {
            get {
                return ResourceManager.GetString("Error_FANSExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select FANS Marketing User.
        /// </summary>
        internal static string Error_FANSMarketingUser {
            get {
                return ResourceManager.GetString("Error_FANSMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS TO BE CONSIDERED is Required..
        /// </summary>
        internal static string Error_FANSTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_FANSTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feasibility is required.
        /// </summary>
        internal static string Error_Feasibility {
            get {
                return ResourceManager.GetString("Error_Feasibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback from SCM field is required (Max 2500 characters)..
        /// </summary>
        internal static string Error_FeedbackFromSCM {
            get {
                return ResourceManager.GetString("Error_FeedbackFromSCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG Stock is required..
        /// </summary>
        internal static string Error_FGStock {
            get {
                return ResourceManager.GetString("Error_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required.
        /// </summary>
        internal static string Error_FileNameList {
            get {
                return ResourceManager.GetString("Error_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Design Engineer.
        /// </summary>
        internal static string Error_FinalDesignEngineer {
            get {
                return ResourceManager.GetString("Error_FinalDesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for Design Change is required.
        /// </summary>
        internal static string Error_FNLDesignChangeAttachment {
            get {
                return ResourceManager.GetString("Error_FNLDesignChangeAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for expected result is required.
        /// </summary>
        internal static string Error_FNLExpectedResultsAttachment {
            get {
                return ResourceManager.GetString("Error_FNLExpectedResultsAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Test Report is Required..
        /// </summary>
        internal static string Error_FNLQATestReport {
            get {
                return ResourceManager.GetString("Error_FNLQATestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select D&amp;D HOD Disposal .
        /// </summary>
        internal static string Error_HODDisposal {
            get {
                return ResourceManager.GetString("Error_HODDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not considered reason field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_HODDisposalreason {
            get {
                return ResourceManager.GetString("Error_HODDisposalreason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons or suggest is required.
        /// </summary>
        internal static string Error_Ifnotfeasiblegivereasonssuggestalternatives {
            get {
                return ResourceManager.GetString("Error_Ifnotfeasiblegivereasonssuggestalternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Option.
        /// </summary>
        internal static string Error_IsApproved {
            get {
                return ResourceManager.GetString("Error_IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCode is required (Max length 255 Char.).
        /// </summary>
        internal static string Error_ItemCode {
            get {
                return ResourceManager.GetString("Error_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_KAPExpectedChange {
            get {
                return ResourceManager.GetString("Error_KAPExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_KAPIComment {
            get {
                return ResourceManager.GetString("Error_KAPIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select KAP Marketing User.
        /// </summary>
        internal static string Error_KAPMarketingUser {
            get {
                return ResourceManager.GetString("Error_KAPMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP TO BE CONSIDERED is Required..
        /// </summary>
        internal static string Error_KAPTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_KAPTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_LightingExpectedChange {
            get {
                return ResourceManager.GetString("Error_LightingExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_LightingIComment {
            get {
                return ResourceManager.GetString("Error_LightingIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Lighting Marketing User.
        /// </summary>
        internal static string Error_LightingMarketingUser {
            get {
                return ResourceManager.GetString("Error_LightingMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting TO BECONSIDERED is Required..
        /// </summary>
        internal static string Error_LightingTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_LightingTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_LUMExpectedChange {
            get {
                return ResourceManager.GetString("Error_LUMExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_LUMIComment {
            get {
                return ResourceManager.GetString("Error_LUMIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select LUM Marketing User.
        /// </summary>
        internal static string Error_LUMMarketingUser {
            get {
                return ResourceManager.GetString("Error_LUMMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM TO BE CONSIDERED is Required..
        /// </summary>
        internal static string Error_LUMTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_LUMTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Marketing Approval is required ?.
        /// </summary>
        internal static string Error_MarketingApproverRequired {
            get {
                return ResourceManager.GetString("Error_MarketingApproverRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR TO BE CONSIDERED is required.
        /// </summary>
        internal static string Error_MarketingDCRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_MarketingDCRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected effect of change on sales field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_MarketingExpectedEffectOfChange {
            get {
                return ResourceManager.GetString("Error_MarketingExpectedEffectOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Comments is required.
        /// </summary>
        internal static string Error_MarketingOverallComments {
            get {
                return ResourceManager.GetString("Error_MarketingOverallComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Marketing User.
        /// </summary>
        internal static string Error_MarketingUser {
            get {
                return ResourceManager.GetString("Error_MarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richard Expected Change field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_MRExpectedChange {
            get {
                return ResourceManager.GetString("Error_MRExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_MRMarketingIComment {
            get {
                return ResourceManager.GetString("Error_MRMarketingIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Morphy Richard Marketing User.
        /// </summary>
        internal static string Error_MRMarketingUser {
            get {
                return ResourceManager.GetString("Error_MRMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richard TO BE CONSIDERED is Required..
        /// </summary>
        internal static string Error_MRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Error_MRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Comments field is required..
        /// </summary>
        internal static string Error_OverallComment {
            get {
                return ResourceManager.GetString("Error_OverallComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Change is required (Max length 15 digit.).
        /// </summary>
        internal static string Error_PercentageChange {
            get {
                return ResourceManager.GetString("Error_PercentageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Test Applicable field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_PerformanceTestApplicable {
            get {
                return ResourceManager.GetString("Error_PerformanceTestApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category is required..
        /// </summary>
        internal static string Error_ProductCategory {
            get {
                return ResourceManager.GetString("Error_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_ProductName {
            get {
                return ResourceManager.GetString("Error_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR To Be Considered is required.
        /// </summary>
        internal static string Error_QADCRToBeConsidered {
            get {
                return ResourceManager.GetString("Error_QADCRToBeConsidered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect of change on quality norms field is required (Max 1000 characters)..
        /// </summary>
        internal static string Error_QAEffectofchangeonqualitynorms {
            get {
                return ResourceManager.GetString("Error_QAEffectofchangeonqualitynorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_QAIComment {
            get {
                return ResourceManager.GetString("Error_QAIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select QA User.
        /// </summary>
        internal static string Error_QAUser {
            get {
                return ResourceManager.GetString("Error_QAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is required.
        /// </summary>
        internal static string Error_Quantity {
            get {
                return ResourceManager.GetString("Error_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot upload files with same name..
        /// </summary>
        internal static string Error_SameFileName {
            get {
                return ResourceManager.GetString("Error_SameFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments field is required (Max 500 characters)..
        /// </summary>
        internal static string Error_SCMIComment {
            get {
                return ResourceManager.GetString("Error_SCMIComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select SCM User.
        /// </summary>
        internal static string Error_SCMUser {
            get {
                return ResourceManager.GetString("Error_SCMUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date Of Implementation is required..
        /// </summary>
        internal static string Error_TargetDateOfImplementation {
            get {
                return ResourceManager.GetString("Error_TargetDateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Benefit / Loss in Rupees is required.
        /// </summary>
        internal static string Error_TotalBenefitLossInRupeesLakhs {
            get {
                return ResourceManager.GetString("Error_TotalBenefitLossInRupeesLakhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expected Quantity in current  year is required.
        /// </summary>
        internal static string Error_TotalExpectedQuantityInCurrentYe {
            get {
                return ResourceManager.GetString("Error_TotalExpectedQuantityInCurrentYe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expected Quantity in next year is required.
        /// </summary>
        internal static string Error_TotalExpectedQuantityInNextYear {
            get {
                return ResourceManager.GetString("Error_TotalExpectedQuantityInNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload test report is required.
        /// </summary>
        internal static string Error_Uploadtestreport {
            get {
                return ResourceManager.GetString("Error_Uploadtestreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor is required.
        /// </summary>
        internal static string Error_Vendor {
            get {
                return ResourceManager.GetString("Error_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name field is required (Max 255 characters)..
        /// </summary>
        internal static string Error_VendorName {
            get {
                return ResourceManager.GetString("Error_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vendor data selected..
        /// </summary>
        internal static string Grid_Text_NoVendorData {
            get {
                return ResourceManager.GetString("Grid_Text_NoVendorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC.
        /// </summary>
        internal static string Grid_Title_CC {
            get {
                return ResourceManager.GetString("Grid_Title_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Increase/Decrease.
        /// </summary>
        internal static string Grid_Title_CostIncreaseDecrease {
            get {
                return ResourceManager.GetString("Grid_Title_CostIncreaseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing.
        /// </summary>
        internal static string Grid_Title_Costing {
            get {
                return ResourceManager.GetString("Grid_Title_Costing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Value.
        /// </summary>
        internal static string Grid_Title_CostValue {
            get {
                return ResourceManager.GetString("Grid_Title_CostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP.
        /// </summary>
        internal static string Grid_Title_DAPMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_DAPMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Application.
        /// </summary>
        internal static string Grid_Title_DateofApplication {
            get {
                return ResourceManager.GetString("Grid_Title_DateofApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Implementation.
        /// </summary>
        internal static string Grid_Title_DateOfImplementation {
            get {
                return ResourceManager.GetString("Grid_Title_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR No..
        /// </summary>
        internal static string Grid_Title_DCRNo {
            get {
                return ResourceManager.GetString("Grid_Title_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of change.
        /// </summary>
        internal static string Grid_Title_DescofChange {
            get {
                return ResourceManager.GetString("Grid_Title_DescofChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Grid_Title_DnD {
            get {
                return ResourceManager.GetString("Grid_Title_DnD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Stock at Warehouse.
        /// </summary>
        internal static string Grid_Title_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Grid_Title_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS.
        /// </summary>
        internal static string Grid_Title_FANSMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_FANSMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Stock.
        /// </summary>
        internal static string Grid_Title_FGStock {
            get {
                return ResourceManager.GetString("Grid_Title_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string Grid_Title_ItemCode {
            get {
                return ResourceManager.GetString("Grid_Title_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP.
        /// </summary>
        internal static string Grid_Title_KAPMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_KAPMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        internal static string Grid_Title_LightingMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_LightingMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM.
        /// </summary>
        internal static string Grid_Title_LUMMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_LUMMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string Grid_Title_Marketing {
            get {
                return ResourceManager.GetString("Grid_Title_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richards.
        /// </summary>
        internal static string Grid_Title_MRMarketing {
            get {
                return ResourceManager.GetString("Grid_Title_MRMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Change.
        /// </summary>
        internal static string Grid_Title_PercentageChange {
            get {
                return ResourceManager.GetString("Grid_Title_PercentageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By.
        /// </summary>
        internal static string Grid_Title_PreparedBy {
            get {
                return ResourceManager.GetString("Grid_Title_PreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string Grid_Title_ProductName {
            get {
                return ResourceManager.GetString("Grid_Title_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        internal static string Grid_Title_QA {
            get {
                return ResourceManager.GetString("Grid_Title_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Grid_Title_Quantity {
            get {
                return ResourceManager.GetString("Grid_Title_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM.
        /// </summary>
        internal static string Grid_Title_SCM {
            get {
                return ResourceManager.GetString("Grid_Title_SCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string Grid_Title_VendorName {
            get {
                return ResourceManager.GetString("Grid_Title_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments:.
        /// </summary>
        internal static string Label_Attachments {
            get {
                return ResourceManager.GetString("Label_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit:.
        /// </summary>
        internal static string Label_BusinessUnit {
            get {
                return ResourceManager.GetString("Label_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not feasible, give reasons and/or suggest alternatives:.
        /// </summary>
        internal static string Label_CCIfNotFeasibleGiveReason {
            get {
                return ResourceManager.GetString("Label_CCIfNotFeasibleGiveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments after proto testing/field trial report etc. where required:.
        /// </summary>
        internal static string Label_CommentsAfterProtoTesting {
            get {
                return ResourceManager.GetString("Label_CommentsAfterProtoTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider/Rework.
        /// </summary>
        internal static string Label_ConsiderRework {
            get {
                return ResourceManager.GetString("Label_ConsiderRework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Increase/Decrease:.
        /// </summary>
        internal static string Label_CostIncreaseDecrease {
            get {
                return ResourceManager.GetString("Label_CostIncreaseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost reduced / Increased by Rs:.
        /// </summary>
        internal static string Label_CostreducedIncreasedbyRs {
            get {
                return ResourceManager.GetString("Label_CostreducedIncreasedbyRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Value:.
        /// </summary>
        internal static string Label_CostValue {
            get {
                return ResourceManager.GetString("Label_CostValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP Expected Change :.
        /// </summary>
        internal static string Label_DAPExpectedChange {
            get {
                return ResourceManager.GetString("Label_DAPExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP Marketing User : .
        /// </summary>
        internal static string Label_DAPMarketingUser {
            get {
                return ResourceManager.GetString("Label_DAPMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP MARKETING TO BE CONSIDERED :.
        /// </summary>
        internal static string Label_DAPTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_DAPTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Completion of Testing:.
        /// </summary>
        internal static string Label_DateForCompletionOfTesting {
            get {
                return ResourceManager.GetString("Label_DateForCompletionOfTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Receipt of Samples:.
        /// </summary>
        internal static string Label_DateForReceiptOfSamples {
            get {
                return ResourceManager.GetString("Label_DateForReceiptOfSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Date:.
        /// </summary>
        internal static string Label_DateOfImplementation {
            get {
                return ResourceManager.GetString("Label_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCRDCN Incharge Comments:.
        /// </summary>
        internal static string Label_DCRDCNInchargeComments {
            get {
                return ResourceManager.GetString("Label_DCRDCNInchargeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Incharge:.
        /// </summary>
        internal static string Label_DCRIncharge {
            get {
                return ResourceManager.GetString("Label_DCRIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Label_DCRInchargeComment {
            get {
                return ResourceManager.GetString("Label_DCRInchargeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Label_DCRInchargeNavigatorComment {
            get {
                return ResourceManager.GetString("Label_DCRInchargeNavigatorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR No.:.
        /// </summary>
        internal static string Label_DCRNo {
            get {
                return ResourceManager.GetString("Label_DCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR to be Considered:.
        /// </summary>
        internal static string Label_DCRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_DCRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D HOD DISPOSAL:.
        /// </summary>
        internal static string Label_DDHODDISPOSAL {
            get {
                return ResourceManager.GetString("Label_DDHODDISPOSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Rework.
        /// </summary>
        internal static string Label_DEIReworkComments {
            get {
                return ResourceManager.GetString("Label_DEIReworkComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        internal static string Label_Department {
            get {
                return ResourceManager.GetString("Label_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of design change proposed:.
        /// </summary>
        internal static string Label_DescriptionOfDesignChangePropose {
            get {
                return ResourceManager.GetString("Label_DescriptionOfDesignChangePropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design change proposed due to:.
        /// </summary>
        internal static string Label_Designchangeproposeddueto {
            get {
                return ResourceManager.GetString("Label_Designchangeproposeddueto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Label_DesignChangeProposedOther {
            get {
                return ResourceManager.GetString("Label_DesignChangeProposedOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design change required by (Date):.
        /// </summary>
        internal static string Label_DesignChangeRequiredByDate {
            get {
                return ResourceManager.GetString("Label_DesignChangeRequiredByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Document Engineer:.
        /// </summary>
        internal static string Label_DesignDocumentEngineer {
            get {
                return ResourceManager.GetString("Label_DesignDocumentEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer:.
        /// </summary>
        internal static string Label_DesignEngineer {
            get {
                return ResourceManager.GetString("Label_DesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer Incharge :.
        /// </summary>
        internal static string Label_DesignEngineerIncharge {
            get {
                return ResourceManager.GetString("Label_DesignEngineerIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer :.
        /// </summary>
        internal static string Label_DesignEngineerUser {
            get {
                return ResourceManager.GetString("Label_DesignEngineerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in components and assembly:.
        /// </summary>
        internal static string Label_Detailsofchangescomponentsassembly {
            get {
                return ResourceManager.GetString("Label_Detailsofchangescomponentsassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in components and assembly:.
        /// </summary>
        internal static string Label_Detailsofchangesincomponents {
            get {
                return ResourceManager.GetString("Label_Detailsofchangesincomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in components and assembly.
        /// </summary>
        internal static string Label_Detailsofchangesincomponentsanda {
            get {
                return ResourceManager.GetString("Label_Detailsofchangesincomponentsanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in tools, jigs and fixtures:.
        /// </summary>
        internal static string Label_Detailsofchangesintoolsjigs {
            get {
                return ResourceManager.GetString("Label_Detailsofchangesintoolsjigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in tools, jigs and fixtures.
        /// </summary>
        internal static string Label_Detailsofchangesintoolsjigsandfi {
            get {
                return ResourceManager.GetString("Label_Detailsofchangesintoolsjigsandfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of changes in tools, jigs and fixtures:.
        /// </summary>
        internal static string Label_Detailsofchangestoolsjigsfixtures {
            get {
                return ResourceManager.GetString("Label_Detailsofchangestoolsjigsfixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division:.
        /// </summary>
        internal static string Label_Division {
            get {
                return ResourceManager.GetString("Label_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect on cost of part and product:.
        /// </summary>
        internal static string Label_Effectoncostofpartandproduct {
            get {
                return ResourceManager.GetString("Label_Effectoncostofpartandproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect on performance:.
        /// </summary>
        internal static string Label_Effectonperformance {
            get {
                return ResourceManager.GetString("Label_Effectonperformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Component Stock.
        /// </summary>
        internal static string Label_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Label_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected effect of change on sales:.
        /// </summary>
        internal static string Label_Expectedeffectofchangeonsales {
            get {
                return ResourceManager.GetString("Label_Expectedeffectofchangeonsales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected results if design change Attachment:.
        /// </summary>
        internal static string Label_Expectedresultattachment {
            get {
                return ResourceManager.GetString("Label_Expectedresultattachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected results if design change is carried out:.
        /// </summary>
        internal static string Label_Expectedresultsifdesignchangeisc {
            get {
                return ResourceManager.GetString("Label_Expectedresultsifdesignchangeisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS Expected Change : .
        /// </summary>
        internal static string Label_FANSExpectedChange {
            get {
                return ResourceManager.GetString("Label_FANSExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS Marketing User : .
        /// </summary>
        internal static string Label_FANSMarketingUser {
            get {
                return ResourceManager.GetString("Label_FANSMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS  MARKETING TO BE CONSIDERED : .
        /// </summary>
        internal static string Label_FANSTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_FANSTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feasibility:.
        /// </summary>
        internal static string Label_Feasibility {
            get {
                return ResourceManager.GetString("Label_Feasibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback from SCM:.
        /// </summary>
        internal static string Label_FeedbackFromSCM {
            get {
                return ResourceManager.GetString("Label_FeedbackFromSCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG Stock.
        /// </summary>
        internal static string Label_FGStock {
            get {
                return ResourceManager.GetString("Label_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Engineer:.
        /// </summary>
        internal static string Label_FinalDesignEngineer {
            get {
                return ResourceManager.GetString("Label_FinalDesignEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design change proposed Attachment:.
        /// </summary>
        internal static string Label_FNLDesignChangeAttachment {
            get {
                return ResourceManager.GetString("Label_FNLDesignChangeAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected results if design change Attachment:.
        /// </summary>
        internal static string Label_FNLExpectedResultsAttachment {
            get {
                return ResourceManager.GetString("Label_FNLExpectedResultsAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Test Report:.
        /// </summary>
        internal static string Label_FNLQATestReport {
            get {
                return ResourceManager.GetString("Label_FNLQATestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D HOD Comments:.
        /// </summary>
        internal static string Label_HODComment {
            get {
                return ResourceManager.GetString("Label_HODComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D HOD Disposal:.
        /// </summary>
        internal static string Label_HODDisposal {
            get {
                return ResourceManager.GetString("Label_HODDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Not Considered (reason):.
        /// </summary>
        internal static string Label_HODDisposalreason {
            get {
                return ResourceManager.GetString("Label_HODDisposalreason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Not Considered (reason):.
        /// </summary>
        internal static string Label_IfNotConsidered {
            get {
                return ResourceManager.GetString("Label_IfNotConsidered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not feasible, give reasons and/or suggest alternatives:.
        /// </summary>
        internal static string Label_Ifnotfeasiblegivereasonssuggestalternatives {
            get {
                return ResourceManager.GetString("Label_Ifnotfeasiblegivereasonssuggestalternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved / Not Approved:.
        /// </summary>
        internal static string Label_IsApproved {
            get {
                return ResourceManager.GetString("Label_IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is DCR Retrieved?.
        /// </summary>
        internal static string Label_IsDCRRetrieved {
            get {
                return ResourceManager.GetString("Label_IsDCRRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code:.
        /// </summary>
        internal static string Label_ItemCode {
            get {
                return ResourceManager.GetString("Label_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP Expected Change : .
        /// </summary>
        internal static string Label_KAPExpectedChange {
            get {
                return ResourceManager.GetString("Label_KAPExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP Marketing User : .
        /// </summary>
        internal static string Label_KAPMarketingUser {
            get {
                return ResourceManager.GetString("Label_KAPMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP MARKETING TO BE CONSIDERED : .
        /// </summary>
        internal static string Label_KAPTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_KAPTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Expected Change : .
        /// </summary>
        internal static string Label_LightingExpectedChange {
            get {
                return ResourceManager.GetString("Label_LightingExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting Marketing User : .
        /// </summary>
        internal static string Label_LightingMarketingUser {
            get {
                return ResourceManager.GetString("Label_LightingMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting MARKETING TO BE CONSIDERED : .
        /// </summary>
        internal static string Label_LightingTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_LightingTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Expected Change : .
        /// </summary>
        internal static string Label_LUMExpectedChange {
            get {
                return ResourceManager.GetString("Label_LUMExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Marketing User : .
        /// </summary>
        internal static string Label_LUMMarketingUser {
            get {
                return ResourceManager.GetString("Label_LUMMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM MARKETING TO BE CONSIDERED : .
        /// </summary>
        internal static string Label_LUMTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_LUMTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Approval Required:.
        /// </summary>
        internal static string Label_MarketingApprovalRequired {
            get {
                return ResourceManager.GetString("Label_MarketingApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Approval Required:.
        /// </summary>
        internal static string Label_MarketingApproverRequired {
            get {
                return ResourceManager.GetString("Label_MarketingApproverRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR TO BE CONSIDERED.
        /// </summary>
        internal static string Label_MarketingDCRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_MarketingDCRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected effect of change on sales:.
        /// </summary>
        internal static string Label_MarketingExpectedEffectOfChange {
            get {
                return ResourceManager.GetString("Label_MarketingExpectedEffectOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Comments:.
        /// </summary>
        internal static string Label_MarketingOverallComment {
            get {
                return ResourceManager.GetString("Label_MarketingOverallComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Comments:.
        /// </summary>
        internal static string Label_MarketingOverallComments {
            get {
                return ResourceManager.GetString("Label_MarketingOverallComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing user:.
        /// </summary>
        internal static string Label_MarketingUser {
            get {
                return ResourceManager.GetString("Label_MarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richard Expected Change : .
        /// </summary>
        internal static string Label_MRExpectedChange {
            get {
                return ResourceManager.GetString("Label_MRExpectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richard Marketing User : .
        /// </summary>
        internal static string Label_MRMarketingUser {
            get {
                return ResourceManager.GetString("Label_MRMarketingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphy Richard MARKETING TO BE CONSIDERED : .
        /// </summary>
        internal static string Label_MRTOBECONSIDERED {
            get {
                return ResourceManager.GetString("Label_MRTOBECONSIDERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Label_NavigatorComment {
            get {
                return ResourceManager.GetString("Label_NavigatorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Label_negativeSign {
            get {
                return ResourceManager.GetString("Label_negativeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old DCR Created Date:.
        /// </summary>
        internal static string Label_OldDCRCreatedDate {
            get {
                return ResourceManager.GetString("Label_OldDCRCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old DCR No.:.
        /// </summary>
        internal static string Label_OldDCRNo {
            get {
                return ResourceManager.GetString("Label_OldDCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old DCR Rejected Date:.
        /// </summary>
        internal static string Label_OldDCRRejectedDate {
            get {
                return ResourceManager.GetString("Label_OldDCRRejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Comments:.
        /// </summary>
        internal static string Label_Overallcomment {
            get {
                return ResourceManager.GetString("Label_Overallcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Change:.
        /// </summary>
        internal static string Label_PercentageChange {
            get {
                return ResourceManager.GetString("Label_PercentageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Test Applicable:.
        /// </summary>
        internal static string Label_PerformanceTestApplicable {
            get {
                return ResourceManager.GetString("Label_PerformanceTestApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category:.
        /// </summary>
        internal static string Label_ProductCategory {
            get {
                return ResourceManager.GetString("Label_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        internal static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR TO BE CONSIDERED.
        /// </summary>
        internal static string Label_QADCRToBeConsidered {
            get {
                return ResourceManager.GetString("Label_QADCRToBeConsidered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect of change on quality norms:.
        /// </summary>
        internal static string Label_QAEffectofchangeonqualitynorms {
            get {
                return ResourceManager.GetString("Label_QAEffectofchangeonqualitynorms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Overall Comment.
        /// </summary>
        internal static string Label_QAOverallComment {
            get {
                return ResourceManager.GetString("Label_QAOverallComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA User:.
        /// </summary>
        internal static string Label_QAUser {
            get {
                return ResourceManager.GetString("Label_QAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string Label_Quantity {
            get {
                return ResourceManager.GetString("Label_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR NO:.
        /// </summary>
        internal static string Label_ReferenceNo {
            get {
                return ResourceManager.GetString("Label_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Comment.
        /// </summary>
        internal static string Label_RejectedComment {
            get {
                return ResourceManager.GetString("Label_RejectedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request/Created By:.
        /// </summary>
        internal static string Label_RequestBy {
            get {
                return ResourceManager.GetString("Label_RequestBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Department:.
        /// </summary>
        internal static string Label_RequestDepartment {
            get {
                return ResourceManager.GetString("Label_RequestDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Rework (reason):.
        /// </summary>
        internal static string Label_ReworkComments {
            get {
                return ResourceManager.GetString("Label_ReworkComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM User:.
        /// </summary>
        internal static string Label_SCMUser {
            get {
                return ResourceManager.GetString("Label_SCMUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM User Comment.
        /// </summary>
        internal static string Label_SCMUserComment {
            get {
                return ResourceManager.GetString("Label_SCMUserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock of old items related to the DCR:.
        /// </summary>
        internal static string Label_StockofolditemsrelatedtotheDCR {
            get {
                return ResourceManager.GetString("Label_StockofolditemsrelatedtotheDCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target date of DCN Release:.
        /// </summary>
        internal static string Label_TargetDateOfImplementation {
            get {
                return ResourceManager.GetString("Label_TargetDateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Benefit / Loss in Rupees:.
        /// </summary>
        internal static string Label_TotalBenefitLossinRupeesLakhs {
            get {
                return ResourceManager.GetString("Label_TotalBenefitLossinRupeesLakhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expected Quantity in current  year:.
        /// </summary>
        internal static string Label_TotalExpectedQuantityincurrentye {
            get {
                return ResourceManager.GetString("Label_TotalExpectedQuantityincurrentye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expected Quantity in next year :.
        /// </summary>
        internal static string Label_TotalExpectedQuantityinnextyear {
            get {
                return ResourceManager.GetString("Label_TotalExpectedQuantityinnextyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload test report:.
        /// </summary>
        internal static string Label_Uploadtestreport {
            get {
                return ResourceManager.GetString("Label_Uploadtestreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor:.
        /// </summary>
        internal static string Label_Vendor {
            get {
                return ResourceManager.GetString("Label_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name:.
        /// </summary>
        internal static string Label_VendorName {
            get {
                return ResourceManager.GetString("Label_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string Label_WorkflowStatus {
            get {
                return ResourceManager.GetString("Label_WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Change Requisition.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        internal static string Popup_Title_AddVendor {
            get {
                return ResourceManager.GetString("Popup_Title_AddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vendor.
        /// </summary>
        internal static string Popup_Title_EditVendor {
            get {
                return ResourceManager.GetString("Popup_Title_EditVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSUMER CARE SECTION.
        /// </summary>
        internal static string Section_Title_CCHead {
            get {
                return ResourceManager.GetString("Section_Title_CCHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing Section.
        /// </summary>
        internal static string Section_Title_costingSection {
            get {
                return ResourceManager.GetString("Section_Title_costingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_DAPMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_DAPMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAP MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_DAPMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_DAPMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate DCR.
        /// </summary>
        internal static string Section_Title_DCRDetails {
            get {
                return ResourceManager.GetString("Section_Title_DCRDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR DETAIL SECTION.
        /// </summary>
        internal static string Section_Title_DCRDetailSection {
            get {
                return ResourceManager.GetString("Section_Title_DCRDetailSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESIGN ENGINEER INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_DESIGNENGINEERINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_DESIGNENGINEERINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESIGN ENGINEER SECTION.
        /// </summary>
        internal static string Section_Title_DesignEngineerSection {
            get {
                return ResourceManager.GetString("Section_Title_DesignEngineerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_FANSMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_FANSMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANS MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_FANSMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_FANSMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;D HOD.
        /// </summary>
        internal static string Section_Title_HOD1Section {
            get {
                return ResourceManager.GetString("Section_Title_HOD1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Considered.
        /// </summary>
        internal static string Section_Title_HOD2Section {
            get {
                return ResourceManager.GetString("Section_Title_HOD2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  D&amp;D SECTION.
        /// </summary>
        internal static string Section_Title_HOD3 {
            get {
                return ResourceManager.GetString("Section_Title_HOD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR PROCESS INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_INCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_INCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR INCHARGE NAVIGATOR SECTION.
        /// </summary>
        internal static string Section_Title_INCHARGESECTIONNavigator {
            get {
                return ResourceManager.GetString("Section_Title_INCHARGESECTIONNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_KAPMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_KAPMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_KAPMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_KAPMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHTING MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_LIGHTINGMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_LIGHTINGMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHTING MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_LIGHTINGMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_LIGHTINGMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_LUMMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_LUMMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_LUMMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_LUMMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETING INCHARGE.
        /// </summary>
        internal static string Section_Title_MKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_MKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_MKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_MKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORPHY RICHARDS MARKETING INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_MRMKTINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_MRMKTINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORPHY RICHARDS MARKETING SECTION.
        /// </summary>
        internal static string Section_Title_MRMKTSECTION {
            get {
                return ResourceManager.GetString("Section_Title_MRMKTSECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print DCR.
        /// </summary>
        internal static string Section_Title_PrintDCR {
            get {
                return ResourceManager.GetString("Section_Title_PrintDCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA SECTION.
        /// </summary>
        internal static string Section_Title_QA {
            get {
                return ResourceManager.GetString("Section_Title_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_QAINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_QAINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SCM SECTION.
        /// </summary>
        internal static string Section_Title_SCM {
            get {
                return ResourceManager.GetString("Section_Title_SCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM and Costing Section.
        /// </summary>
        internal static string Section_Title_SCMCOSTINGINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_SCMCOSTINGINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM INCHARGE SECTION.
        /// </summary>
        internal static string Section_Title_SCMINCHARGESECTION {
            get {
                return ResourceManager.GetString("Section_Title_SCMINCHARGESECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Grid.
        /// </summary>
        internal static string Section_Title_Vendor {
            get {
                return ResourceManager.GetString("Section_Title_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Completed successfully.
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR delegated successfully.
        /// </summary>
        internal static string Text_DelegatedSuccess {
            get {
                return ResourceManager.GetString("Text_DelegatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR Rejected/Not Consider successfully..
        /// </summary>
        internal static string Text_RejectedSuccess {
            get {
                return ResourceManager.GetString("Text_RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR saved successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCR submitted successfully.
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vendor name is already added.
        /// </summary>
        internal static string Text_UniqeVendor {
            get {
                return ResourceManager.GetString("Text_UniqeVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details is deleted.
        /// </summary>
        internal static string Text_VendorDeleted {
            get {
                return ResourceManager.GetString("Text_VendorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one Vendor data requried.
        /// </summary>
        internal static string Text_VendorRequired {
            get {
                return ResourceManager.GetString("Text_VendorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details is saved.
        /// </summary>
        internal static string Text_VendorSave {
            get {
                return ResourceManager.GetString("Text_VendorSave", resourceCulture);
            }
        }
    }
}
